# Generated by Django 5.1.4 on 2024-12-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, help_text='Introduce la dirección del usuario.', max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.CharField(blank=True, help_text='Nombre de la empresa.', max_length=100, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(blank=True, help_text='Introduce un número de teléfono válido.', null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(help_text='Introduce el apellido del usuario.', max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(help_text='Introduce un correo electrónico válido.', max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(help_text='Introduce el nombre del usuario.', max_length=100, verbose_name='Nombre'),
        ),
    ]
