# Generated by Django 5.1.4 on 2024-12-10 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuario', '0002_usuario_direccion_usuario_empresa_usuario_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Introduce el nombre del usuario.', max_length=100, verbose_name='Nombre')),
                ('acceso', models.IntegerField(blank=True, help_text='Introduce el nivel de acceso del usuario.', null=True, verbose_name='Acceso')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField(blank=True, help_text='Introduce el usuario asignado.', null=True, verbose_name='Usuario')),
                ('fecha_solicitud', models.DateField()),
                ('nombre', models.CharField(blank=True, help_text='Introduce que solicita.', max_length=100, null=True, verbose_name='Nombre de la solicitud')),
                ('descripcion', models.CharField(blank=True, help_text='Introduce lo que busca.', max_length=300, null=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el usuario está activo.', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=1, help_text='Rol asignado al usuario.', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='app_usuario.rol', verbose_name='Rol'),
        ),
    ]
