# Generated by Django 5.1.4 on 2024-12-10 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuario', '0003_rol_solicitudservicio_usuario_activo_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudservicio',
            name='nombre',
            field=models.CharField(blank=True, help_text='Introduce que solicita.', max_length=100, null=True, verbose_name='Título de la solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Introduce el usuario asignado.', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_usuario.usuario', verbose_name='Usuario'),
        ),
    ]
